# ----------------------------------------------------------------------------------------------------------------------

# Problem 2 - Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms...
# ...By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,...
# ...find the sum of the even-valued terms.

# ----------------------------------------------------------------------------------------------------------------------

initial_term = 1
new_term = 2

even_numbers = []

while new_term <= 4000000:
    new_term = initial_term + new_term
    initial_term = new_term - initial_term

    if not initial_term % 2:
        even_numbers.append(initial_term)

print(sum(even_numbers))

