# ----------------------------------------------------------------------------------------------------------------------

# Problem 4 - Largest palindrome product

# A palindromic number reads the same both ways. The largest palindrome made...
# ...from the product of two 2-digit numbers is 9009 = 91 × 99.
# Find the largest palindrome made from the product of two 3-digit numbers.

# ----------------------------------------------------------------------------------------------------------------------


# Largest number that can be generated by multiplying 3 digits is 998001
# 999 * 999 = 998001

# Smallest number that can be generated by multiplying 3 digits is 10000
# 100 * 100 = 10000

def largest_palindrome():
    for i in range(998001, 10000, -1):
        i = str(i)
        if i[:3] == i[3:][::-1]:
            for j in range(999, 99, -1):
                for k in range(j, 99, -1):
                    # If j*k < i: skip to next iteration to save time
                    if j * k < int(i):
                        break
                    if j * k == int(i):
                        print("Largest palindrome: ", i, " -> ", j, " * ", k)
                        return


largest_palindrome()
